[project]
site_name = "Guides Not Included"
site_description = "A popular website with guides for Oxygen Not Included revived from the depths of web archive."
site_author = "hadook"
site_url = "https://hadook.github.io/guides-not-included"

repo_url = "https://github.com/hadook/guides-not-included"
repo_name = "hadook/guides-not-included"

nav = [
  { "Home" = "index.md" },
  { "Builds" = "builds.md" },
  { "Guides" = "guides.md" },
  { "Resources" = "resources.md" },
  { "About" = "about.md" },
  { "Zensical" = "zensical.md" },
]

[project.theme]
# variant = "classic"
favicon = "img/icon-duplicant.png"
language = "en"

features = [
    "announce.dismiss",
    #"content.action.edit",
    # "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    # "header.autohide",
    # "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    #"navigation.prune",
    "navigation.sections",
    # "navigation.tabs",
    # "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    # "toc.integrate",
]

# logo = "img/icon-duplicant.png"

[project.theme.icon]
# logo = "lucide/book-open"
repo = "fontawesome/brands/github"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
